/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "../Inc/MCAL_RCC_INC/RCC_interface.h"
#include "../Inc/MCAL_GPIO_INC/GPIO_interface.h"
#include "../Inc/MCAL_STK_INC/STK_interface.h"
#include "../Inc/RTOS_INC/RTOS_interface.h"
RCC_HSI_Config_t  RCC_HSI_Configs  = {HSION};
RCC_HSE_Config_t  RCC_HSE_Configs  = {HSEON,HSEBYPON};
RCC_GPIO_Config_t RCC_GPIO_Configs = {GPIOA_ENABLED,GPIOB_ENABLED,GPIOC_ENABLED,GPIOD_ENABLED,GPIOE_ENABLED,GPIOF_ENABLED,GPIOG_ENABLED,GPIOH_ENABLED};
/***** Pins Configurations*****/
PinConfig_t 	  PA0_Configs      = {PORTA, 0, OUTPUT,LOW,OPEN_DRAIN,PULLDOWN,AF0};
PinConfig_t 	  PA1_Configs      = {PORTA, 1, OUTPUT,LOW,OPEN_DRAIN,PULLDOWN,AF0};
PinConfig_t 	  PA4_Configs      = {PORTA, 4, OUTPUT,LOW,OPEN_DRAIN,PULLDOWN,AF0};
PinConfig_t 	  PA5_Configs      = {PORTA, 5, OUTPUT,LOW,OPEN_DRAIN,PULLDOWN,AF0};
PinConfig_t 	  PA6_Configs      = {PORTA, 6, OUTPUT,LOW,OPEN_DRAIN,PULLDOWN,AF0};
PinConfig_t 	  PC0_Configs      = {PORTC, 0, OUTPUT,LOW,OPEN_DRAIN,PULLDOWN,AF0};
PinConfig_t 	  PC1_Configs      = {PORTC, 1, OUTPUT,LOW,OPEN_DRAIN,PULLDOWN,AF0};

//SysTickConfig_t   SysTickConfigs   = {AHB,TICKINT_ENABLED};
void TogglePin(void);
void LED1(void);
void LED2(void);
void LED3(void);

int main(void)
{
	//RCC_Set_HSI(&RCC_HSI_Configs);
	RCC_Set_HSE(&RCC_HSE_Configs);

	RCC_GPIO_Init(&RCC_GPIO_Configs);

	/***** Pins Initializations*****/
	GPIO_u8PinInit(&PA0_Configs);
	GPIO_u8PinInit(&PA1_Configs);
	GPIO_u8PinInit(&PA4_Configs);
	GPIO_u8PinInit(&PA5_Configs);
	GPIO_u8PinInit(&PC0_Configs);
	GPIO_u8PinInit(&PC1_Configs);
	//GPIO_u8PinInit(&PA6_Configs);

	//SysTick_Init(&SysTickConfigs);
	//Systick_CallBack(&RTOS_Scheduler);
	//SysTick_Start(1000);
	/*
	GPIO_u8PinInit(&PA5_Configs);
	GPIO_SetPinValue(PORTA, 5, 1);
	*/
	//GPIO_u8TogglePinValue(PORTA, 5);
	//GPIO_u8SetPinValue(PORTA, 5, HIGHVAL);
	/*RTOS*/
	RTOS_CreateTask(0, 1000, &LED1);
	RTOS_CreateTask(1, 2000, &LED2);
	RTOS_CreateTask(2, 3000, &LED3);

	RTOS_Start();
    /* Loop forever */
	for(;;)
	{


		//GPIO_u8TogglePinValue(PORTA, 5);
		SysTick_Delay_ms(1000000);


	}
}
void LED1(void)
{
	GPIO_u8TogglePinValue(PORTA, 5);
}
void LED2(void)
{
	GPIO_u8TogglePinValue(PORTC, 0);
}
void LED3(void)
{
	GPIO_u8TogglePinValue(PORTC, 1);
}

